"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { motion } from "framer-motion";
import { ArrowLeft, ArrowUpRight, BookOpen, Search, ShieldCheck, FileKey2, LockKeyhole, Globe2, Binary, Workflow, ChevronDown, CircleHelp, Cpu, Layers3, CheckCircle2, UnlockKeyhole } from "lucide-react";
import "./tutorial.css";

type Block = { title: string; body: string };
type Lesson = { id: string; title: string; eyebrow: string; icon: typeof BookOpen; intro: string; blocks: Block[] };
const lessons: Lesson[] = [
{ id:"basics", title:"Understanding PlayStation Save Files", eyebrow:"START HERE", icon:BookOpen, intro:"A save file is more than a document. It can combine game progress, metadata, account association and protection data, all of which need to remain compatible with the game and console.", blocks:[
{title:"What is Save Wizard?",body:"Save Wizard is a save-management solution for PlayStation 4 that supports workflows such as resigning compatible saves for another account and applying supported save modifications. QoiaX Wizard presents save-management workflows in a browser-based workspace; actual operations depend on the compatible processing service behind the interface."},
{title:"What can a save contain?",body:"Depending on the game and format, files may include game data, title identifiers such as a CUSA code, account-related values, metadata, checksums, authentication values or encrypted content. An incorrect structure or incompatible metadata can cause a save to be rejected or ignored."},
{title:"Compatibility matters",body:"Compatibility can depend on the game version, title ID, account association, save structure and processing method. A tool reporting that processing completed does not guarantee that every game will accept the result."}]},
{ id:"security", title:"PlayStation Security Architecture", eyebrow:"CORE CONCEPTS", icon:ShieldCheck, intro:"Several distinct mechanisms may protect a save. Understanding what each one does helps avoid confusing encryption with account association or integrity validation.", blocks:[
{title:"File structure and metadata",body:"Metadata describes a save’s identity and internal organization. CUSA identifiers distinguish PS4 game releases or title variants. Incorrect metadata or a mismatched structure may make a save incompatible."},
{title:"Account association",body:"Some saves are associated with the PlayStation Network account that created them. The underlying account identifier is different from the public Online ID displayed as a username."},
{title:"Encryption",body:"Encryption transforms data into ciphertext. Recovering the original content requires the appropriate key and a compatible decryption process. Renaming a file or editing a few hexadecimal bytes does not decrypt it."},
{title:"Integrity and authentication",body:"Checksums, authentication values and digital signatures can detect changes or help establish authenticity. These mechanisms have a different purpose from encryption, which primarily protects confidentiality."},
{title:"Compatibility validation",body:"The console and game must interpret the save correctly. Account association, identifiers, metadata, file structure and game-specific requirements may all affect whether it can be loaded."}]},
{ id:"encrypt-decrypt", title:"Encrypt & Decrypt", eyebrow:"FILE WORKFLOWS", icon:LockKeyhole, intro:"Encryption and decryption are related operations, but neither one automatically makes a save compatible with a different account or game release.", blocks:[
{title:"What Encrypt means",body:"Encryption transforms data into a protected representation using a cryptographic algorithm and the appropriate key. In save management, it may prepare supported data for a format or workflow that expects encrypted content. The exact process depends on the file format and implementation."},
{title:"What Decrypt means",body:"Decryption reverses a compatible encryption operation and recovers the original data when the correct key and parameters are available. A decrypted file is not necessarily ready to copy back to a console; its structure, metadata and integrity information must still be valid."},
{title:"Before you begin",body:"Keep an untouched backup of original files. Use only files and file pairs expected by the selected workflow, and do not assume that changing a file extension changes its contents."}]},
{ id:"resign", title:"Resign a Save", eyebrow:"ACCOUNT WORKFLOW", icon:FileKey2, intro:"Resigning prepares a supported save for association with a different PlayStation account. It is not simply a matter of renaming the file or replacing a visible username.", blocks:[
{title:"Why account details matter",body:"A save created by one account may contain account-related information that prevents another account from using it directly. A compatible resigning workflow processes relevant account-associated fields and any supported authentication or integrity structures."},
{title:"Online ID vs Account ID",body:"The PlayStation Network Online ID is the visible profile username. The Account ID is a separate internal identifier. Some PS4 save formats represent an Account ID as eight bytes, which can be displayed as sixteen hexadecimal characters because each hexadecimal character represents four bits."},
{title:"Use the correct target",body:"Supply the intended target account information in the format required by the workflow. The exact representation and byte order depend on the save format; not every sixteen-character hexadecimal string is automatically a valid Account ID."},
{title:"What success means",body:"A completed resign operation does not guarantee that every game or save version is compatible. Preserve the original and validate the result using the relevant game and workflow requirements."}]},
{ id:"reregion", title:"Change a Save Region", eyebrow:"TITLE COMPATIBILITY", icon:Globe2, intro:"Reregion adapts a save from one supported game region or title variant to another compatible variant. It is different from changing the account associated with a save.", blocks:[
{title:"Understanding CUSA",body:"PS4 games use title identifiers commonly called CUSA identifiers to distinguish releases. Regional variants may have different identifiers and can also differ in save structure or content layout."},
{title:"Typical two-step workflow",body:"First, identify the intended target release and provide any reference save or target information the tool requires. Then select the source save to convert. Exact steps depend on the supported conversion method."},
{title:"When conversion may not work",body:"A conversion is not guaranteed when source and target game versions use incompatible save structures. Confirm title IDs and game versions, and keep a backup before attempting conversion."}]},
{ id:"hex", title:"Hexadecimal & Binary", eyebrow:"TECHNICAL BASICS", icon:Binary, intro:"Hexadecimal is a compact way to display binary data. It is a representation of data, not an encryption method by itself.", blocks:[
{title:"Bits, bytes and hex",body:"Computers represent information as binary digits, zero and one. Hexadecimal is base sixteen and uses 0–9 and A–F. One hexadecimal digit represents four bits; two hexadecimal digits represent one byte, or eight bits."},
{title:"A small example",body:"The hexadecimal byte 4A represents the binary value 01001010. The hex form is shorter to read, but the meaning of a byte still depends on the format that defines it."},
{title:"Why context matters",body:"Bytes in a save may represent identifiers, counters, structured metadata, compressed content, encrypted data or other fields. Reading or editing a value without understanding its format does not automatically reveal or safely change its meaning."}]},
{ id:"workflow", title:"What Happens Behind the Interface", eyebrow:"HOW THE WORKFLOW FITS TOGETHER", icon:Workflow, intro:"A browser interface and the component that transforms save data are separate parts of the system.", blocks:[
{title:"1 · Select and validate",body:"The user selects files and an operation. The interface can check basic details such as file names, sizes and whether required inputs appear to be present."},
{title:"2 · Submit for processing",body:"A compatible processing service receives the request, checks whether the files match its supported workflow, and applies the format-specific logic and cryptographic capabilities available to it."},
{title:"3 · Return the result",body:"The service returns the resulting file or an error. The website presents the result for download. The browser UI alone does not automatically have console-specific cryptographic capabilities."},
{title:"A note about connection status",body:"A visual Connected/Not Connected indicator should reflect a real health check when one is implemented. A display setting alone is not proof that the processing service is reachable."}]},
{ id:"apollo", title:"Apollo Save Tool & Web Tools", eyebrow:"TOOLS AND EXECUTION MODELS", icon:Cpu, intro:"Different save-management tools can run in different environments, and their capabilities depend on the platform and permissions available.", blocks:[
{title:"Apollo Save Tool",body:"Apollo Save Tool is a save-management utility for supported PlayStation platforms. On a compatible jailbroken PS4, it can provide supported save operations directly in the console environment. Available features depend on firmware, permissions and the operation being performed."},
{title:"How a web-based system differs",body:"A web tool can send selected files to a compatible backend service, which performs supported transformations and returns the result. The browser itself does not gain access to required algorithms or keys simply because a file is uploaded."},
{title:"QoiaX Wizard",body:"QoiaX Wizard is designed as a browser-based workspace for save-management workflows, including Resign, Encrypt, Decrypt, Reregion and CUSA lookup. Actual processing capability depends on the connected backend and its supported formats."}]}
];

export default function TutorialPage(){
 const [query,setQuery]=useState(""); const [expanded,setExpanded]=useState<string[]>(["basics"]);
 const filtered=useMemo(()=>lessons.filter(l=>`${l.title} ${l.eyebrow} ${l.intro} ${l.blocks.map(b=>`${b.title} ${b.body}`).join(" ")}`.toLowerCase().includes(query.toLowerCase())),[query]);
 const toggle=(id:string)=>setExpanded(c=>c.includes(id)?c.filter(x=>x!==id):[...c,id]);
 return <main className="site-shell tutorial-shell"><div className="ambient ambient-one" aria-hidden="true"/><div className="ambient ambient-two" aria-hidden="true"/>
 <header className="topbar tutorial-topbar"><Link className="brand-lockup" href="/" aria-label="QoiaX Wizard home"><span className="brand-mark">Q<span>×</span></span><span className="brand-words"><strong>QoiaX</strong><small>WIZARD</small></span></Link><nav className="top-nav" aria-label="Tutorial navigation"><Link href="/#tools">Tools</Link><span className="tutorial-nav-current">Tutorial</span><Link className="nav-cta" href="/forge?tab=resign">Open Wizard <ArrowUpRight size={15}/></Link></nav></header>
 <section className="tutorial-hero"><motion.div className="tutorial-hero-copy" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.55}}><Link href="/" className="tutorial-back"><ArrowLeft size={15}/> Back to workspace</Link><div className="eyebrow"><span className="eyebrow-dot"/> QOIAX KNOWLEDGE CENTER</div><h1>Understand the<br/><span>save system.</span></h1><p>A guided, visual introduction to PS4 save files, account identifiers, encryption, resigning and region compatibility.</p><div className="tutorial-hero-stats"><span><BookOpen size={15}/> {lessons.length} learning modules</span><span><Layers3 size={15}/> Beginner to technical</span></div></motion.div>
 <motion.div className="tutorial-orb-scene" initial={{opacity:0,scale:.9,rotate:-5}} animate={{opacity:1,scale:1,rotate:0}} transition={{duration:.8,delay:.12}} aria-hidden="true"><div className="tutorial-orb-glow"/><div className="tutorial-orbit orbit-one"><i/></div><div className="tutorial-orbit orbit-two"><i/></div><div className="tutorial-orbit orbit-three"><i/></div><div className="tutorial-orb"><div className="tutorial-orb-grid"/><div className="tutorial-orb-core"><Cpu size={36}/></div></div><span className="tutorial-orb-label label-top">DATA / STRUCTURE</span><span className="tutorial-orb-label label-bottom">QX LEARNING SYSTEM</span></motion.div></section>
 <section className="tutorial-search-panel glass-panel"><div className="tutorial-search-copy"><span className="section-kicker">THE FIELD GUIDE</span><h2>What do you want to understand?</h2><p>Search across the tutorial, or open a module below.</p></div><label className="tutorial-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search encryption, CUSA, Account ID…" aria-label="Search tutorial"/>{query&&<button onClick={()=>setQuery("")} aria-label="Clear search">Clear</button>}</label></section>
 <div className="tutorial-layout"><aside className="tutorial-sidebar glass-panel"><span className="section-kicker">CONTENTS</span><div className="tutorial-sidebar-list">{lessons.map((l,i)=><a key={l.id} href={`#${l.id}`} className="tutorial-sidebar-link"><span>{String(i+1).padStart(2,"0")}</span>{l.title}</a>)}</div><div className="tutorial-sidebar-note"><ShieldCheck size={17}/><p>Keep original save files backed up before attempting any modification.</p></div></aside>
 <section className="tutorial-lessons" aria-label="Tutorial modules">{filtered.length===0&&<div className="tutorial-empty glass-panel"><CircleHelp size={28}/><h3>No matching lesson</h3><p>Try a different keyword, such as “hex”, “region” or “account”.</p></div>}
 {filtered.map((lesson,index)=>{const Icon=lesson.icon;const isOpen=expanded.includes(lesson.id)||!!query;return <motion.article id={lesson.id} key={lesson.id} className={`tutorial-lesson glass-panel ${isOpen?"is-open":""}`} initial={{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.08}} transition={{duration:.35,delay:Math.min(index*.025,.15)}}><button className="tutorial-lesson-trigger" onClick={()=>toggle(lesson.id)} aria-expanded={isOpen}><span className="tutorial-lesson-icon"><Icon size={21}/></span><span className="tutorial-lesson-heading"><span className="section-kicker">{lesson.eyebrow} · MODULE {String(lessons.findIndex(x=>x.id===lesson.id)+1).padStart(2,"0")}</span><strong>{lesson.title}</strong><small>{lesson.intro}</small></span><span className="tutorial-lesson-toggle"><ChevronDown size={19}/></span></button>
 {isOpen&&<motion.div className="tutorial-lesson-content" initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} transition={{duration:.25}}><p className="tutorial-intro">{lesson.intro}</p><div className="tutorial-topic-grid">{lesson.blocks.filter(b=>!query||`${b.title} ${b.body}`.toLowerCase().includes(query.toLowerCase())||lesson.title.toLowerCase().includes(query.toLowerCase())).map((block,i)=><div className="tutorial-topic" key={block.title}><div className="tutorial-topic-index"><span>{String(i+1).padStart(2,"0")}</span><span className="topic-line"/></div><div><h3>{block.title}</h3><p>{block.body}</p></div></div>)}</div><div className="tutorial-lesson-foot"><span><CheckCircle2 size={15}/> Learning note</span><span>{lesson.blocks.length} topics</span></div></motion.div>}</motion.article>})}</section></div>
 <section className="tutorial-disclaimer glass-panel"><div className="tutorial-disclaimer-icon"><ShieldCheck size={22}/></div><div><span className="section-kicker">A QUICK REMINDER</span><h2>Compatibility comes first.</h2><p>Save formats differ between games and versions. Keep backups, use files you are entitled to manage, and treat a completed workflow as a result to validate—not a guarantee that every title will accept the save.</p></div><Link href="/cusa" className="text-link">Explore CUSA Database <ArrowUpRight size={16}/></Link></section>
 <footer className="site-footer"><span className="footer-brand">QoiaX Wizard</span><span className="footer-dot"/><span>Knowledge Center</span><span className="footer-spacer"/><span className="footer-note">Learn the structure · Understand the workflow</span></footer></main>;
}
